# Generated by Django 2.1.4 on 2018-12-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='name',
            new_name='number',
        ),
        migrations.AddField(
            model_name='test',
            name='password',
            field=models.CharField(default='lap', max_length=20),
            preserve_default=False,
        ),
    ]
