# Generated by Django 2.1.4 on 2018-12-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryId', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('authorId', models.CharField(max_length=20)),
                ('remark', models.CharField(max_length=100)),
            ],
        ),
    ]
